version: "3.7"
# This is the dev compose-file, we don't have a prod one yet

services:
  spigot:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "22"
      - "25565"
      - "8123"
    ports:
      - "2220:22" # ssh -p 2220 pingu@localhost (you will need to make ssh keys)
      - "25565:25565"
      - "8123:8123"
    volumes: 
      - "mc:/spigot"
    environment: 
      START_RAM_USAGE: "2G" # DISCUSS/CONSIDER?/...w/e
      MAX_RAM_USAGE: "8G"   # DISCUSS/CONSIDER?/...w/e
      EULA: "TRUE"

volumes:
  mc:
    name: "mc"
