version: "3.7"
# This is the dev compose-file, we don't have a prod one yet

services:
  spigot:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "22"
      - "25565"
    ports:
      - "2220:22" # ssh -p 2220 pingu@localhost (add your public sshkey to authorized_keys)
      - "25565:25565" # for some reason other ports aren't working
    # volumes: 
      # - spigot:/spigot/
      # - spigot2:/spigot2/
    environment:
      START_RAM_USAGE: "2G"
      MAX_RAM_USAGE: "8G"

volumes: 
  spigot:
    name: "spigot"
  spigot2:
    name: "spigot2"

# > core protect  > mysql
# > dynmap        > webb


# ---
#
# how the volumes look: an example
#
#services
#  ubuntu:
#    volumes:
#      - ubuntu-data:/home
#
#volumes:
#  ubuntu-data:
#    name: "ubuntu-data"    # the name tag might be redundant, I don't actually know
#
# ---
