version: "3.7"
# This is the dev compose-file, we don't have a prod one yet

services:
  spigot:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "22"
      - "25565"
      - "8123"
    ports:
      - "2220:22"     # ssh
      - "25565:25565" # minecraft
      - "8123:8123"   # dynmap
      - "25575:25575" # rcon
    volumes: 
      - ./mc:/data
    environment: 
      START_RAM_USAGE: "2G"
      MAX_RAM_USAGE: "8G"
      EULA: "TRUE"

# volumes:
#   mc:
#     name: "mc"
