version: "3.7"
# This is the dev compose-file, we don't have a prod one yet

services:

  sqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./db_data:/var/lib/mysql"
      - "./docker-scripts:/docker-entrypoint-initdb.d"
    restart: unless-stopped
    expose:
      - "3306"
    environment: 
      MYSQL_ROOT_PASSWORD: skt
      MYSQL_USER: pingu
      MYSQL_PASSWORD: skt
    networks:
      - mcnet

  spigot:
    restart: unless-stopped
    depends_on: 
      - sqldb
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - sqldb:sqldb
    ports:
      - "2220:22"     # ssh
      - "25565:25565" # minecraft
      - "8123:8123"   # dynmap
    volumes: 
      - "./mc:/data"
    environment: 
      XMS: "1G" # Starting Memory
      XMX: "4G" # Max Memory Usage
      EULA: "TRUE"
    networks: 
      - mcnet

networks:
  mcnet:

